title = "Oberhauser Foundation News"
copyright = "Oberhauser Foundation"
baseURL = "https://blog.oberhauser.foundation"
languageCode = "en-us"
theme = "default"

# Needed for github pages
publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = "UA-171612832-2"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    # pre = "<i class='fa fa-heart'></i>"
    url = "https://oberhauser.foundation/"
    weight = 1
  [[menu.main]]
    identifier = "fund-structure"
    name = "Fund Structure"
    # pre = "<i class='fa fa-heart'></i>"
    url = "https://oberhauser.foundation/#section-foundation"
    weight = 2
  [[menu.main]]
    identifier = "2-about"
    name = "About"
    # pre = "<i class='fa fa-heart'></i>"
    url = "https://oberhauser.foundation/#section-about"
    weight = 3

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/logo.png"
  show_reading_time = true
  description = "The official news source of the Oberhauser Foundation"
  custom_css = ["css/custom.css"]
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/oberhauser-foundation/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "/index.xml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-of-custom"
  featured_image = "/images/header-background.jpg"
  recent_posts_number = 10
